# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'child.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChildWindow(object):
    def setupUi(self, ChildWindow):
        ChildWindow.setObjectName("ChildWindow")
        ChildWindow.resize(791, 594)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("SAPLogon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ChildWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ChildWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 551))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.getTaxpayerTab = QtWidgets.QWidget()
        self.getTaxpayerTab.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.getTaxpayerTab.setMouseTracking(False)
        self.getTaxpayerTab.setObjectName("getTaxpayerTab")
        self.lineEdit_tax_id = QtWidgets.QLineEdit(self.getTaxpayerTab)
        self.lineEdit_tax_id.setGeometry(QtCore.QRect(220, 20, 211, 31))
        self.lineEdit_tax_id.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_tax_id.setText("")
        self.lineEdit_tax_id.setObjectName("lineEdit_tax_id")
        self.label_tax_id = QtWidgets.QLabel(self.getTaxpayerTab)
        self.label_tax_id.setGeometry(QtCore.QRect(10, 20, 201, 31))
        self.label_tax_id.setObjectName("label_tax_id")
        self.label_check_id = QtWidgets.QLabel(self.getTaxpayerTab)
        self.label_check_id.setGeometry(QtCore.QRect(10, 70, 201, 31))
        self.label_check_id.setObjectName("label_check_id")
        self.lineEdit_check_id = QtWidgets.QLineEdit(self.getTaxpayerTab)
        self.lineEdit_check_id.setGeometry(QtCore.QRect(220, 70, 211, 31))
        self.lineEdit_check_id.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_check_id.setText("")
        self.lineEdit_check_id.setObjectName("lineEdit_check_id")
        self.tabWidget.addTab(self.getTaxpayerTab, "")
        self.checkInvoiceTab = QtWidgets.QWidget()
        self.checkInvoiceTab.setObjectName("checkInvoiceTab")
        self.label_inv_num_check = QtWidgets.QLabel(self.checkInvoiceTab)
        self.label_inv_num_check.setGeometry(QtCore.QRect(10, 70, 181, 31))
        self.label_inv_num_check.setObjectName("label_inv_num_check")
        self.lineEdit_inv_num_check = QtWidgets.QLineEdit(self.checkInvoiceTab)
        self.lineEdit_inv_num_check.setGeometry(QtCore.QRect(190, 70, 201, 31))
        self.lineEdit_inv_num_check.setObjectName("lineEdit_inv_num_check")
        self.label_direction_check = QtWidgets.QLabel(self.checkInvoiceTab)
        self.label_direction_check.setGeometry(QtCore.QRect(10, 120, 181, 31))
        self.label_direction_check.setObjectName("label_direction_check")
        self.comboBox_direction_check = QtWidgets.QComboBox(self.checkInvoiceTab)
        self.comboBox_direction_check.setGeometry(QtCore.QRect(190, 120, 201, 31))
        self.comboBox_direction_check.setObjectName("comboBox_direction_check")
        self.label_tax_id_check = QtWidgets.QLabel(self.checkInvoiceTab)
        self.label_tax_id_check.setGeometry(QtCore.QRect(10, 20, 181, 31))
        self.label_tax_id_check.setObjectName("label_tax_id_check")
        self.lineEdit_tax_id_check = QtWidgets.QLineEdit(self.checkInvoiceTab)
        self.lineEdit_tax_id_check.setGeometry(QtCore.QRect(190, 20, 201, 31))
        self.lineEdit_tax_id_check.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_tax_id_check.setText("")
        self.lineEdit_tax_id_check.setObjectName("lineEdit_tax_id_check")
        self.label = QtWidgets.QLabel(self.checkInvoiceTab)
        self.label.setGeometry(QtCore.QRect(10, 200, 131, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(5)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.checkInvoiceTab)
        self.line.setGeometry(QtCore.QRect(10, 180, 371, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.checkInvoiceTab)
        self.label_2.setGeometry(QtCore.QRect(10, 245, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(5)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.checkInvoiceTab, "")
        self.getInvoiceDataTab = QtWidgets.QWidget()
        self.getInvoiceDataTab.setObjectName("getInvoiceDataTab")
        self.label_inv_num_dat = QtWidgets.QLabel(self.getInvoiceDataTab)
        self.label_inv_num_dat.setGeometry(QtCore.QRect(10, 70, 181, 31))
        self.label_inv_num_dat.setObjectName("label_inv_num_dat")
        self.lineEdit_inv_num_dat = QtWidgets.QLineEdit(self.getInvoiceDataTab)
        self.lineEdit_inv_num_dat.setGeometry(QtCore.QRect(190, 70, 201, 31))
        self.lineEdit_inv_num_dat.setObjectName("lineEdit_inv_num_dat")
        self.label_tax_id_dat = QtWidgets.QLabel(self.getInvoiceDataTab)
        self.label_tax_id_dat.setGeometry(QtCore.QRect(10, 20, 181, 31))
        self.label_tax_id_dat.setObjectName("label_tax_id_dat")
        self.lineEdit_tax_id_dat = QtWidgets.QLineEdit(self.getInvoiceDataTab)
        self.lineEdit_tax_id_dat.setGeometry(QtCore.QRect(190, 20, 201, 31))
        self.lineEdit_tax_id_dat.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_tax_id_dat.setText("")
        self.lineEdit_tax_id_dat.setObjectName("lineEdit_tax_id_dat")
        self.label_direction_dat = QtWidgets.QLabel(self.getInvoiceDataTab)
        self.label_direction_dat.setGeometry(QtCore.QRect(10, 120, 181, 31))
        self.label_direction_dat.setObjectName("label_direction_dat")
        self.comboBox_direction_dat = QtWidgets.QComboBox(self.getInvoiceDataTab)
        self.comboBox_direction_dat.setGeometry(QtCore.QRect(190, 120, 201, 31))
        self.comboBox_direction_dat.setObjectName("comboBox_direction_dat")
        self.scrollArea = QtWidgets.QScrollArea(self.getInvoiceDataTab)
        self.scrollArea.setGeometry(QtCore.QRect(410, 19, 361, 461))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 459))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.line_dat = QtWidgets.QFrame(self.getInvoiceDataTab)
        self.line_dat.setGeometry(QtCore.QRect(10, 180, 381, 16))
        self.line_dat.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_dat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_dat.setObjectName("line_dat")
        self.label_resp_dat = QtWidgets.QLabel(self.getInvoiceDataTab)
        self.label_resp_dat.setGeometry(QtCore.QRect(10, 200, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_resp_dat.setFont(font)
        self.label_resp_dat.setObjectName("label_resp_dat")
        self.label_source_dat = QtWidgets.QLabel(self.getInvoiceDataTab)
        self.label_source_dat.setGeometry(QtCore.QRect(10, 250, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_source_dat.setFont(font)
        self.label_source_dat.setObjectName("label_source_dat")
        self.label_trans_dat = QtWidgets.QLabel(self.getInvoiceDataTab)
        self.label_trans_dat.setGeometry(QtCore.QRect(10, 275, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_trans_dat.setFont(font)
        self.label_trans_dat.setObjectName("label_trans_dat")
        self.label_index_dat = QtWidgets.QLabel(self.getInvoiceDataTab)
        self.label_index_dat.setGeometry(QtCore.QRect(10, 300, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(5)
        self.label_index_dat.setFont(font)
        self.label_index_dat.setObjectName("label_index_dat")
        self.label_reqv_dat = QtWidgets.QLabel(self.getInvoiceDataTab)
        self.label_reqv_dat.setGeometry(QtCore.QRect(10, 330, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(5)
        self.label_reqv_dat.setFont(font)
        self.label_reqv_dat.setObjectName("label_reqv_dat")
        self.label_inv_save_time_dat = QtWidgets.QLabel(self.getInvoiceDataTab)
        self.label_inv_save_time_dat.setGeometry(QtCore.QRect(10, 355, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(5)
        self.label_inv_save_time_dat.setFont(font)
        self.label_inv_save_time_dat.setObjectName("label_inv_save_time_dat")
        self.label_tech_user_dat = QtWidgets.QLabel(self.getInvoiceDataTab)
        self.label_tech_user_dat.setGeometry(QtCore.QRect(10, 385, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(5)
        self.label_tech_user_dat.setFont(font)
        self.label_tech_user_dat.setObjectName("label_tech_user_dat")
        self.pushButton_save_dat = QtWidgets.QPushButton(self.getInvoiceDataTab)
        self.pushButton_save_dat.setGeometry(QtCore.QRect(690, 480, 81, 31))
        self.pushButton_save_dat.setObjectName("pushButton_save_dat")
        self.pushButton = QtWidgets.QPushButton(self.getInvoiceDataTab)
        self.pushButton.setGeometry(QtCore.QRect(614, 480, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.getInvoiceDataTab, "")
        ChildWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChildWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 21))
        self.menubar.setObjectName("menubar")
        ChildWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChildWindow)
        self.statusbar.setObjectName("statusbar")
        ChildWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChildWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(ChildWindow)

    def retranslateUi(self, ChildWindow):
        _translate = QtCore.QCoreApplication.translate
        ChildWindow.setWindowTitle(_translate("ChildWindow", "Hungary-tool"))
        self.getTaxpayerTab.setToolTip(_translate("ChildWindow", "<html><head/><body><p>get taxpayer validity</p></body></html>"))
        self.lineEdit_tax_id.setToolTip(_translate("ChildWindow", "<html><head/><body><p>taxpayer id of your company</p></body></html>"))
        self.label_tax_id.setText(_translate("ChildWindow", "Taxpayer ID:"))
        self.label_check_id.setText(_translate("ChildWindow", "Taxpayer ID to check:"))
        self.lineEdit_check_id.setToolTip(_translate("ChildWindow", "<html><head/><body><p>taxpayer id for company that you want to check</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.getTaxpayerTab), _translate("ChildWindow", "Check taxpayer"))
        self.label_inv_num_check.setText(_translate("ChildWindow", "Invoice Number:"))
        self.lineEdit_inv_num_check.setToolTip(_translate("ChildWindow", "<html><head/><body><p>Invoice number to check</p></body></html>"))
        self.label_direction_check.setText(_translate("ChildWindow", "Direction:"))
        self.comboBox_direction_check.setToolTip(_translate("ChildWindow", "<html><head/><body><p>Direction of invoice can be INBOUND and OUTBOUND.</p><p>OUTBOUND is your own invoice, and INBOUND is invoice of other company</p></body></html>"))
        self.label_tax_id_check.setText(_translate("ChildWindow", "Taxpayer ID:"))
        self.lineEdit_tax_id_check.setToolTip(_translate("ChildWindow", "<html><head/><body><p>taxpayer id of your company</p></body></html>"))
        self.label.setText(_translate("ChildWindow", "Response data:"))
        self.label_2.setToolTip(_translate("ChildWindow", "<html><head/><body><p>Contains the boolean result of the check</p></body></html>"))
        self.label_2.setText(_translate("ChildWindow", "Check result:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.checkInvoiceTab), _translate("ChildWindow", "Check Invoice"))
        self.label_inv_num_dat.setText(_translate("ChildWindow", "Invoice Number:"))
        self.lineEdit_inv_num_dat.setToolTip(_translate("ChildWindow", "<html><head/><body><p>invoice number to get data </p></body></html>"))
        self.label_tax_id_dat.setText(_translate("ChildWindow", "Taxpayer ID:"))
        self.lineEdit_tax_id_dat.setToolTip(_translate("ChildWindow", "<html><head/><body><p>taxpayer id of your company</p></body></html>"))
        self.label_direction_dat.setText(_translate("ChildWindow", "Direction:"))
        self.comboBox_direction_dat.setToolTip(_translate("ChildWindow", "<html><head/><body><p>Direction of invoice can be INBOUND and OUTBOUND.</p><p>OUTBOUND is your own invoice, and INBOUND is invoice of other company</p></body></html>"))
        self.label_resp_dat.setText(_translate("ChildWindow", "Response data:"))
        self.label_source_dat.setToolTip(_translate("ChildWindow", "<html><head/><body><p>Invoice data report source</p></body></html>"))
        self.label_source_dat.setText(_translate("ChildWindow", "Source:"))
        self.label_trans_dat.setToolTip(_translate("ChildWindow", "<html><head/><body><p>Invoice data report transaction ID, if the report was submitted via the computer interface</p></body></html>"))
        self.label_trans_dat.setText(_translate("ChildWindow", "Transaction ID"))
        self.label_index_dat.setToolTip(_translate("ChildWindow", "<html><head/><body><p>Invoice data report transaction index</p></body></html>"))
        self.label_index_dat.setText(_translate("ChildWindow", "Index:"))
        self.label_reqv_dat.setToolTip(_translate("ChildWindow", "<html><head/><body><p>Data report requestVersion value </p></body></html>"))
        self.label_reqv_dat.setText(_translate("ChildWindow", "Original request version:"))
        self.label_inv_save_time_dat.setToolTip(_translate("ChildWindow", "<html><head/><body><p>Invoice data report save time </p></body></html>"))
        self.label_inv_save_time_dat.setText(_translate("ChildWindow", "Invoice data save time:"))
        self.label_tech_user_dat.setToolTip(_translate("ChildWindow", "<html><head/><body><p>Name of the technical user submitting the invoice data report</p></body></html>"))
        self.label_tech_user_dat.setText(_translate("ChildWindow", "Technical user name:"))
        self.pushButton_save_dat.setToolTip(_translate("ChildWindow", "<html><head/><body><p>save invoice file </p><p><br/></p></body></html>"))
        self.pushButton_save_dat.setText(_translate("ChildWindow", "Save"))
        self.pushButton.setToolTip(_translate("ChildWindow", "<html><head/><body><p>clear current response</p></body></html>"))
        self.pushButton.setText(_translate("ChildWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.getInvoiceDataTab), _translate("ChildWindow", "Get Invoice data"))
