# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(733, 485)
        MainWindow.setBaseSize(QtCore.QSize(700, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("SAPLogon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ContinueButton = QtWidgets.QPushButton(self.centralwidget)
        self.ContinueButton.setGeometry(QtCore.QRect(440, 300, 181, 51))
        self.ContinueButton.setObjectName("ContinueButton")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(10, 46, 321, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.label_name.setFont(font)
        self.label_name.setScaledContents(False)
        self.label_name.setObjectName("label_name")
        self.label_pass = QtWidgets.QLabel(self.centralwidget)
        self.label_pass.setGeometry(QtCore.QRect(10, 100, 311, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.label_pass.setFont(font)
        self.label_pass.setObjectName("label_pass")
        self.label_cred = QtWidgets.QLabel(self.centralwidget)
        self.label_cred.setGeometry(QtCore.QRect(10, 170, 321, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.label_cred.setFont(font)
        self.label_cred.setObjectName("label_cred")
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(350, 40, 271, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pass.setGeometry(QtCore.QRect(350, 100, 271, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.lineEdit_pass.setFont(font)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.SeeButton = QtWidgets.QPushButton(self.centralwidget)
        self.SeeButton.setGeometry(QtCore.QRect(630, 110, 41, 31))
        self.SeeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SeeButton.setIcon(icon1)
        self.SeeButton.setIconSize(QtCore.QSize(55, 45))
        self.SeeButton.setObjectName("SeeButton")
        self.lineEdit_addr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_addr.setGeometry(QtCore.QRect(210, 219, 411, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.lineEdit_addr.setFont(font)
        self.lineEdit_addr.setObjectName("lineEdit_addr")
        self.label_tenant = QtWidgets.QLabel(self.centralwidget)
        self.label_tenant.setGeometry(QtCore.QRect(10, 220, 161, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.label_tenant.setFont(font)
        self.label_tenant.setObjectName("label_tenant")
        self.PingButton = QtWidgets.QPushButton(self.centralwidget)
        self.PingButton.setGeometry(QtCore.QRect(260, 300, 181, 51))
        self.PingButton.setObjectName("PingButton")
        self.label_ping = QtWidgets.QLabel(self.centralwidget)
        self.label_ping.setGeometry(QtCore.QRect(630, 222, 81, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.label_ping.setFont(font)
        self.label_ping.setText("")
        self.label_ping.setObjectName("label_ping")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 733, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hungary-tool"))
        MainWindow.setToolTip(_translate("MainWindow", "Hungary tool"))
        self.ContinueButton.setText(_translate("MainWindow", "Continue"))
        self.label_name.setText(_translate("MainWindow", "CPI User name: "))
        self.label_pass.setText(_translate("MainWindow", "CPI user password:"))
        self.label_cred.setText(_translate("MainWindow", "Credentials are empty"))
        self.lineEdit_name.setToolTip(_translate("MainWindow", "<html><head/><body><p>name of tenant user</p></body></html>"))
        self.lineEdit_pass.setToolTip(_translate("MainWindow", "<html><head/><body><p>password for specified user name</p></body></html>"))
        self.SeeButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>check password</p></body></html>"))
        self.lineEdit_addr.setToolTip(_translate("MainWindow", "<html><head/><body><p>address of deployed Hungarian API iflow </p></body></html>"))
        self.label_tenant.setText(_translate("MainWindow", "Iflow address:"))
        self.PingButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Perform the check of connection with specified iflow with current credentials</p></body></html>"))
        self.PingButton.setText(_translate("MainWindow", "Ping Tenant"))
